import { expect, test, type Page } from "@playwright/test"

const PROJECT_NAME = "Container Onboarding"
const PROJECT_SLUG = "container-onboarding"

async function openLanding(page: Page): Promise<void> {
	await page.goto("/?from=app")
	await expect(
		page.getByRole("button", { name: "New Project", exact: true }),
	).toBeVisible()
	await expect(page.getByRole("button", { name: "Mock", exact: true })).toBeVisible()
	await expect(page.getByText("OpenRouter", { exact: false })).toHaveCount(0)
	await expect(page.getByText("Cerebras", { exact: false })).toHaveCount(0)
}

async function expectGeneratedArtifact(page: Page): Promise<void> {
	await expect(
		page.locator(".agent-hud__agent", {
			hasText: "Hello! I generated a text artifact for validation:",
		}),
	).toBeVisible()

	const link = page.getByRole("link", { name: "Open the generated text file" })
	await expect(link).toBeVisible()
	const popupPromise = page.waitForEvent("popup")
	await link.click()
	const popup = await popupPromise
	await expect(popup.locator("body")).toContainText(
		"Generated by the Robozium mock agent.",
	)
	await popup.close()
}

test("a fresh clone completes the first-use browser journey", async ({ page }) => {
	test.skip(
		process.env.ROBOZIUM_CONTAINER_PHASE === "persistence",
		"persistence phase selected",
	)

	await openLanding(page)
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	await page.getByLabel("Project name").fill(PROJECT_NAME)
	await page.getByRole("button", { name: "Create Project" }).click()
	await expect(page).toHaveURL(/[?&]runId=/)

	await expectGeneratedArtifact(page)
	const textarea = page.locator(".agent-hud__textarea")
	await textarea.fill("first container reply")
	await page.getByRole("button", { name: "Send", exact: true }).click()
	await expect(
		page.locator(".agent-hud__agent", {
			hasText: "Thanks. One more thing before I finish?",
		}),
	).toBeVisible()

	await textarea.fill("second container reply")
	await page.getByRole("button", { name: "Send", exact: true }).click()
	await expect.poll(() => new URL(page.url()).searchParams.get("runId")).toBeNull()
	await expect(
		page.getByRole("button", { name: `Open ${PROJECT_SLUG}`, exact: true }),
	).toBeVisible()
})

test("the first-use project survives API replacement", async ({ page }) => {
	test.skip(
		process.env.ROBOZIUM_CONTAINER_PHASE !== "persistence",
		"onboarding phase selected",
	)

	await openLanding(page)
	await page
		.getByRole("button", { name: `Open ${PROJECT_SLUG}`, exact: true })
		.click()
	await expect(page).toHaveURL(/[?&]runId=/)
	await expectGeneratedArtifact(page)
})
