import fs from "node:fs/promises"
import path from "node:path"
import { expect, test } from "./fixtures"
import { createProject, e2eProjectPaths, gotoLanding, projectRow, selectHudView, waitForProjectRowStatus } from "./helpers"
import { waitForHudLayout } from "./hud-layout"

test("new projects choose capabilities once and cancelled drafts are discarded", async ({ page, request }) => {
	await gotoLanding(page)
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	const selector = page.getByRole("form", { name: "Capability selector" })
	const name = `Capabilities ${Date.now()}`
	await selector.getByLabel("Project name").fill(name)
	await expect(selector.getByRole("button", { name: "Launch", exact: true })).toBeEnabled()
	await selector.getByLabel("Project name").press("Enter")
	await expect(selector.getByLabel("Project name")).toHaveValue(name)
	await expect(page).not.toHaveURL(/[?&]runId=/)
	await expect(selector.getByRole("checkbox", { name: /filesystem/ })).toBeChecked()
	await expect(selector.getByRole("checkbox", { name: /filesystem/ })).toBeDisabled()
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).check()
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).press("Space")
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).not.toBeChecked()
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).press("Enter")
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).toBeChecked()
	await selectHudView(page, "Dependencies")
	await expect(selector).toHaveCount(0)
	await selectHudView(page, "Runs Overview")
	await expect(page.getByRole("button", { name: "New Project", exact: true })).toBeVisible()
	await selectHudView(page, "Launch")
	await expect(selector.getByLabel("Project name")).toHaveValue(name)
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).toBeChecked()
	await selector.getByRole("button", { name: "Cancel", exact: true }).click()
	await expect(page.locator(".agent-hud__view-trigger")).toHaveText("Runs Overview")
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	await expect(selector.getByLabel("Project name")).toHaveValue("")
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).not.toBeChecked()
	await selector.getByLabel("Project name").fill(name)
	await selector.getByRole("checkbox", { name: /mock guidance/ }).check()
	await selector.getByRole("button", { name: "Launch", exact: true }).press("Enter")
	await expect(page).toHaveURL(/[?&]runId=/)
	const runId = new URL(page.url()).searchParams.get("runId")!
	const response = await request.get(`/api/runs/${encodeURIComponent(runId)}/view`)
	expect(response.ok()).toBeTruthy()
	expect((await response.json()).capabilities).toMatchObject({ mock_information: false, mock_guidance: "on_demand" })
	await expect(page.locator(".agent-hud__textarea")).toBeVisible()
	await selectHudView(page, "Runs Overview")
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	await selector.getByLabel("Project name").fill("Unsubmitted draft")
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).check()
	// Escape outside the form dismisses the HUD; inside it cancels the selector.
	await page.getByRole("button", { name: "Toggle color theme", exact: true }).press("Escape")
	await expect(page.locator(".agent-hud")).toHaveClass(/agent-hud--hidden/)
	await page.getByRole("button", { name: "Expand", exact: true }).click()
	await expect(selector).toHaveCount(0)
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	await expect(selector.getByLabel("Project name")).toHaveValue("")
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).not.toBeChecked()
})

test("Launch uses defaults directly after cancelling a Tools selection", async ({ page, request }) => {
	const slug = await createProject(request, `Default Launch ${Date.now()}`)
	await gotoLanding(page)
	const row = projectRow(page, slug)
	await row.getByRole("button", { name: "Tools", exact: true }).click()
	const selector = page.getByRole("form", { name: "Capability selector" })
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).check()
	await selector.getByRole("button", { name: "Cancel", exact: true }).click()
	await row.getByRole("button", { name: "Launch", exact: true }).click()
	await expect(page).toHaveURL(/[?&]runId=/)
	await expect(selector).toHaveCount(0)
	const runId = new URL(page.url()).searchParams.get("runId")!
	const response = await request.get(`/api/runs/${encodeURIComponent(runId)}/view`)
	expect(response.ok()).toBeTruthy()
	expect((await response.json()).capabilities).toMatchObject({ mock_information: false, mock_guidance: false })
})

test("relaunch uses fresh choices while project memory survives", async ({ page, request }) => {
	const slug = await createProject(request, `Relaunch Capabilities ${Date.now()}`)
	const { memory } = e2eProjectPaths(slug)
	await fs.mkdir(memory, { recursive: true })
	const sentinel = path.join(memory, "preferences.md")
	await fs.writeFile(sentinel, "Retain these project preferences.")
	await gotoLanding(page)
	const row = projectRow(page, slug)
	await row.getByRole("button", { name: "Tools", exact: true }).click()
	const selector = page.getByRole("form", { name: "Capability selector" })
	await expect(selector.getByRole("textbox")).toHaveCount(0)
	await expect(selector.getByRole("heading", { name: `Project: ${slug}`, exact: true })).toBeVisible()
	await selectHudView(page, "Dependencies")
	await selectHudView(page, "Launch")
	await expect(selector.getByRole("heading", { name: `Project: ${slug}`, exact: true })).toBeVisible()
	await selector.getByRole("checkbox", { name: "mock information", exact: true }).check()
	await selector.getByRole("button", { name: "Launch", exact: true }).click()
	await expect(page).toHaveURL(/[?&]runId=/)
	const firstRun = new URL(page.url()).searchParams.get("runId")!
	await expect(page.locator(".agent-hud__textarea")).toBeVisible()
	await gotoLanding(page)
	await expect(row.getByRole("button", { name: "Launch", exact: true })).toBeDisabled()
	await expect(row.getByRole("button", { name: "Tools", exact: true })).toBeDisabled()
	await request.post(`/api/projects/${encodeURIComponent(slug)}/cancel`)
	await waitForProjectRowStatus(page, slug, "DORMANT")
	await row.getByRole("button", { name: "Tools", exact: true }).click()
	await expect(selector.getByRole("checkbox", { name: "mock information", exact: true })).not.toBeChecked()
	await selector.getByRole("button", { name: "Launch", exact: true }).click()
	await expect(page).toHaveURL(/[?&]runId=/)
	const secondRun = new URL(page.url()).searchParams.get("runId")!
	expect(secondRun).not.toBe(firstRun)
	const response = await request.get(`/api/runs/${encodeURIComponent(secondRun)}/view`)
	expect((await response.json()).capabilities).toMatchObject({ mock_information: false, mock_guidance: false })
	expect(await fs.readFile(sentinel, "utf8")).toBe("Retain these project preferences.")
})

test("the compact table and selector fit the HUD in both themes", async ({ page, request }) => {
	await page.setViewportSize({ width: 1440, height: 1000 })
	const slug = await createProject(request, `Layout Capabilities ${Date.now()}`)
	await gotoLanding(page)
	for (const theme of ["dark", "light"]) {
		await page.evaluate((value) => document.documentElement.setAttribute("data-theme", value), theme)
		await waitForHudLayout(page)
		const headings = page.locator(".agent-hud__table-header")
		await expect(headings.getByText("Agent", { exact: true })).toHaveCount(0)
		const project = await headings.getByText("Project", { exact: true }).boundingBox()
		const started = await headings.getByText("Started", { exact: true }).boundingBox()
		expect(started!.x - project!.x).toBeLessThan(280)
		await projectRow(page, slug).getByRole("button", { name: "Tools", exact: true }).click()
		const selector = page.getByRole("form", { name: "Capability selector" })
		await expect(selector.getByRole("button", { name: "Launch", exact: true })).toBeEnabled()
		await waitForHudLayout(page)
		const hud = await page.locator(".agent-hud__box").boundingBox()
		const form = await selector.boundingBox()
		expect(form!.y + form!.height).toBeLessThanOrEqual(hud!.y + hud!.height)
		await selector.press("Escape")
		await expect(selector).toHaveCount(0)
	}
})

test("launch failure remains visible after the HUD is dismissed", async ({ page, request }) => {
	const slug = await createProject(request, `Failure active ${Date.now()}`)
	await gotoLanding(page)
	await projectRow(page, slug).getByRole("button", { name: "Launch", exact: true }).click()
	await expect(page.locator(".agent-hud__textarea")).toBeVisible()
	await selectHudView(page, "Runs Overview")
	await page.getByRole("button", { name: "New Project", exact: true }).click()
	const selector = page.getByRole("form", { name: "Capability selector" })
	await selector.getByLabel("Project name").fill(`Failed launch ${Date.now()}`)
	let release!: () => void
	const gate = new Promise<void>((resolve) => { release = resolve })
	let arrived = false
	await page.route("**/api/runs/create", async (route) => {
		arrived = true
		await gate
		await route.fulfill({ status: 409, contentType: "application/json", body: JSON.stringify({ detail: "Project has an active run" }) })
	})
	try {
		await selector.getByRole("button", { name: "Launch", exact: true }).click()
		await expect.poll(() => arrived).toBe(true)
		await page.getByRole("button", { name: "Toggle color theme", exact: true }).press("Escape")
		await expect(page.locator(".agent-hud")).toHaveClass(/agent-hud--hidden/)
		await expect(selector).toHaveCount(0)
		const failed = page.waitForResponse((response) => response.url().endsWith("/api/runs/create"))
		release()
		expect((await failed).status()).toBe(409)
		await page.getByRole("button", { name: "Expand", exact: true }).click()
		await expect(page.getByRole("button", { name: "New Project", exact: true })).toBeEnabled()
		await expect(page.getByText("Project has an active run", { exact: true })).toBeVisible()
		await expect(page.getByText("Launch failed", { exact: true })).toBeVisible()
	} finally {
		release()
		await page.unrouteAll({ behavior: "wait" })
	}
})
