"""Application-owned names persisted in run logs and rendered by the UI."""
ORCHESTRATOR_AGENT_NAME = "orchestrator"
LIBRARIAN_AGENT_NAME = "librarian"
START_BACKGROUND_AGENT_TOOL_NAME = "start_background_agent"
SNAPSHOT_CONVERSATIONS_TOOL_NAME = "snapshot_conversations"
CONSOLIDATE_MEMORY_TOOL_NAME = "consolidate_memory"
PURGE_LOGS_TOOL_NAME = "purge_logs"
PURGE_MEMORY_TOOL_NAME = "purge_memory"
PURGE_SNAPSHOTS_TOOL_NAME = "purge_snapshots"
SLEEP_BETWEEN_RUNS_TOOL_NAME = "sleep_between_runs"
